### ISSUE TITLE
Plan for 1.0.0 release?

### ISSUE THREAD

**Issue by voxpelli** [tellnes/bunyan-middleware#16]
With the two latest version being backwards compatible with just some new features it feels like this project is getting fairly mature and that it may be time for a `1.0.0` release?

As any `0.x` release from a Semantic Versioning perspective is considered to be breaking the release of a `1.0.0` would better communicate the nature of new releases and make it easier to automatically keep up to date with this module.

**Comment by tellnes** [comment]
Yeah, but I'll want to solve issue #14 first. It may require some breaking changes to fix that cleanly.

**Comment by voxpelli** [comment]
1.0.0 has been released :)
