### ISSUE TITLE
Feature Request: Log request information in "start request" log message

### ISSUE THREAD

**Issue by loudwinston** [tellnes/bunyan-middleware#2]
Currently the request information is only logged in the "end request" log message.  It might be helpful to also (optionally?) log it in the "start request" message.

If you think this is a valid feature I'd be happy to submit a pull request for it.

**Comment by tellnes** [comment]
It did work like that before, but I changed it because I did find it easier to read the logs when everything is displayed together.

I'll accept a pull request which making it configurable.

**Comment by kingcody** [comment]
@loudwinston with the current master branch of this project, you can specify `verbose: true` as an option to enable verbose logging as you have requested.
